spring:
  application:
    name: api
    security:
      jwt:
        secret-key: f5f089c5324dcbf107086b08bb7f874bcbf683745484b6684df6d7fc9e591fea
        expiration: 86400000
        refresh-token:
          expiration: 604800000

  datasource:
    url: jdbc:sqlserver://surveysystem.database.windows.net:1433;databaseName=surveysystemdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: surveysystemadmin@surveysystem
    password: '!kBo66q}HjT#r7fieg'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect


logging:
  level:
    org.springframework:
      security: debug
    org.hibernate: debug


server:
  port: 9191

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs