trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      options: 'clean build'
      tasks: 'test'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/build/test-results/test/*.xml'

  - task: Bash@3
    displayName: 'Verificar cambios y hacer merge'
    inputs:
      targetType: 'inline'
      script: |
        echo "Comprobando si las pruebas pasaron..."
        if grep -q "<failure" build/test-results/test/*.xml; then
          echo "Las pruebas fallaron. No se puede hacer el merge."
          exit 1
        else
          echo "Todas las pruebas pasaron. Haciendo merge del pull request..."
          git checkout main
          git merge --no-ff origin/$(System.PullRequest.SourceBranch)
        fi